spring:
  batch:
    job:
      enabled: false
  security:
    enabled: false

jwt:
  validity-time: 10m # minute
  issuer: Hotel-java
  secret: Object-oriented programming is a programming paradigm based on the concept of objects, which can contain data and code

hotel-java.iamport:
  apiKey: 6318782456272832
  apiSecret: drziCrVVErSjpA7mal4EKUNrTuGa1Gf6oG0keXXRO6cs2AVo5YVZGeAuUZsry2YfKtTSVFZFnmcIlWIv

hotel-java.batch:
  stock:
    chunkSize: 10
    day: 30
    quantity: 10
